# vim: set expandtab shiftwidth=2 softtabstop=2 :

language: cpp
sudo: required
service:
- docker

env:
  global:
  - MY_CC=gcc
  - MY_CXX=g++
  - MY_NAME=travis-ci
  - MY_TARGET_MOUNT=/tell/pbkz
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
    - MY_TARGET_DIST=ubuntu:18.04
    - MY_MODE=build
  - os: linux
    dist: trusty
    compiler: gcc
    env:
    - MY_TARGET_DIST=ubuntu:18.04
    - MY_MODE=cppcheck

before_install:
- export CC=$MY_CC
- export CXX=$MY_CXX
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash

install:
- docker exec -ti $MY_NAME bash -c "apt update" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y build-essential" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y libgmp-dev libmpfr-dev libgsl-dev libboost-all-dev" > /dev/null
- if [ "$MY_MODE" == "cppcheck" ] ; then docker exec -ti $MY_NAME bash -c "apt install -y cppcheck" > /dev/null ; fi

before_script:
- docker exec -ti $MY_NAME bash -c "$CC --version"
- docker exec -ti $MY_NAME bash -c "$CXX --version"
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT ; pwd ; ls -la"
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT ; make submods && touch submod.done" | cat -n | awk '{ print $1 }' | sed -n -e 's/[05]00$/*/p'
- ls -la $TRAVIS_BUILD_DIR

script:
- if [ "$MY_MODE" == "build" ] ; then docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT ; make" ; fi
- if [ "$MY_MODE" == "cppcheck" ] ; then docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT ; if which cppcheck; then find pbkzlib -iname '*.cpp' -exec cppcheck --enable=all --force -I `pwd`/pbkzlib -I `pwd`/prefix/include {} \\; ; fi" ; fi

notifications:
  on_success: change
  on_failure: always
